### ISSUE TITLE
Hi, could you explain the following line 

### ISSUE THREAD

**Issue by nile649** [WeiWangTrento/Robust-Differentiable-SVD#1]
https://github.com/WeiWangTrento/Robust-Differentiable-SVD/blob/ee0daa654c11b5abef44dc433d13744be12dd0b7/torch_utils.py#L133

How did you decide exponent (n) value, in your code I see that you're doing iteration till n=9.

**Comment by WeiWangTrento** [comment]
A too large exponent will result in instability when training Cifar10. You can refer to Figure 5 in the paper "Robust Differentiable SVD".  But for large scale dataset, such as Tiny ImageNet, you can increase it to 19 or a larger value since the covariance matrix maybe healthier as its chance to be ill-conditioned is small.

**Comment by nile649** [comment]
Cool, thanks
